### ISSUE TITLE
not changing this class to logger

### ISSUE THREAD

**Issue by nagkumar** [openrewrite/rewrite-logging-frameworks#113]
```
package dev.simonverhoeven.openrewritedemo.oldorgname;

import java.math.BigDecimal;
import java.util.Optional;

public class Sample
{
    public void sampleFunction()
    {
	Boolean sample = true;
	BigDecimal versionCost = BigDecimal.valueOf(8);
	versionCost.setScale(2, 1);

	Optional<String> emptyOptional = Optional.empty();
	boolean isOptionalEmpty = !emptyOptional.isPresent();

	String text = String.format("This is really %s", "outdated");

	String paragraph = "It is really annoying\n" +
			   "that we have to\n" +
			   "keep adding\n" +
			   "these line breaks\n";
	System.out.println("No Logger in this class" + paragraph + text);
    }
}

```

**Comment by nagkumar** [comment]
only if the classs has predefined 

`    Logger logger = LoggerFactory.getLogger(Sample.class);
`

then only it is changing system.outs

**Comment by timtebeek** [comment]
Hi @nagkumar, I'm lacking a bit of context to your question, as it's not clear what recipe you're running, and how you've configured OpenRewrite. Please use the provided templates when opening new issues, as that helps us understand your questions better without having to ask for more input.

I'll assume you ran https://docs.openrewrite.org/recipes/java/logging/systemouttologging, but did not configure the optional fields to add a specific logger. We do not add any particular logger by default, as there's multiple options to chose from, and the specifics will depend on your project. So be sure to provide those values and the recipe should behave as you expect.

If you still have issues beyond that, feel free to reopen this issue with additional details such that we can help you further.
