### ISSUE TITLE
SystemErrToLogging and SystemOutToLogging have identical display name

### ISSUE THREAD

**Issue by Bananeweizen** [openrewrite/rewrite-logging-frameworks#116]
See https://docs.openrewrite.org/recipes/java/logging
![grafik](https://github.com/openrewrite/rewrite-logging-frameworks/assets/406876/1c6f56d5-a4ec-4e1c-9df5-d5c9a9d48e0a)

## Are you interested in [contributing a fix to OpenRewrite](https://github.com/openrewrite/.github/blob/main/CONTRIBUTING.md#contributing-fixes)?

Yes, seems simple. :)

**Comment by timtebeek** [comment]
Thanks for reporting and fixing this issue! Appreciated as always.
