### ISSUE TITLE
Add a JUL to Log4j API conversion

### ISSUE THREAD

**Issue by ppkarwasz** [openrewrite/rewrite-logging-frameworks#132]
## What problem are you trying to solve?

Some users are migrating code from `java.util.logging` to Log4j API (cf. apache/logging-log4j2#2083), therefore it would be useful to have a recipe to convert JUL to Log4j API.

This issue can be split into two parts:

 - the basic methods such as [`Logger#fine`](https://docs.oracle.com/en/java/javase/21/docs/api/java.logging/java/util/logging/Logger.html#fine(java.lang.String)) and [`Logger#getLogger`](https://docs.oracle.com/en/java/javase/21/docs/api/java.logging/java/util/logging/Logger.html#getLogger(java.lang.String)) can be rewritten declaratively,
 - more advanced methods, such as [`Logger#log(Level, String, Object[])`](https://docs.oracle.com/en/java/javase/21/docs/api/java.logging/java/util/logging/Logger.html#log(java.util.logging.Level,java.lang.String,java.lang.Object%5B%5D)) that emulates parameterized logging will probably require some logic to be applied. In the cased of "alternative parameterized logging" a [`MessageFormatMessageFactory`](https://logging.apache.org/log4j/2.x/javadoc/log4j-api/org/apache/logging/log4j/message/MessageFormatMessageFactory.html) instance is required.

I can provide a short-term PR for the first part, while the second part requires more work (but is also only useful to a handful of users).

**Comment by timtebeek** [comment]
Probably best tackled in two separate PRs indeed. Do I understand correctly you aim to work on this as well?

For the second part of more advanced methods you're welcome to start a draft PR with just some tests, such that we can more clearly see what needs to be covered, and how to fill in the blanks on a dedicated recipe.

**Comment by ppkarwasz** [comment]
@timtebeek,

Yes, I will work on it. It is well within the scope of apache/logging-log4j2#2080 and we have users interested in it.

**Comment by timtebeek** [comment]
Great, thanks a lot! Let me know if you need any help; either here or on [our public Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA)
