### ISSUE TITLE
Recipe for migrating from JUL to slf4j? With support for `Logger.log(Level,String)` calls?

### ISSUE THREAD

**Issue by timtebeek** [openrewrite/rewrite-logging-frameworks#155]
### Discussed in https://github.com/openrewrite/rewrite/discussions/4249

<sup>Originally posted by **woj-tek** June 13, 2024</sup>

For a long time we were using JUL (`java.util.Logger`, I know, bad!) and we kinda got stuck with it. However, it's getting more and more annoying to deal with it and it's high time to migrate to slf4j. I was looking for recipes to do so but found none.

I found, somewhat related, [Migrate JUL to Log4j 2.x API](https://docs.openrewrite.org/recipes/java/logging/log4j/jultolog4j) (with the hope to use [Migrate Log4j to SLF4J](https://docs.openrewrite.org/recipes/java/logging/slf4j/log4jtoslf4j)) but the first one didn't work because we rely heavily on `Logger.log(Level,[message])` API instead of `Logger.<level>(<message>)` one which seems to be supported by looking at Definition and method signature.

Does anyone know any recipe for `Logger.log(Level,String)` calls?

**Comment by timtebeek** [comment]
hi @woj-tek; sounds like this is something that we can fairly easily implement with recipes, especially given the examples already available. Is that something you'd like to get involved with? Even just some unit tests could help speed up development.

**Comment by timtebeek** [comment]
Yes that type of test would be perfect to capture exactly what you're after, and then know when we're done with the recipe implementation. Don't worry about getting things to work perfectly just yet; that's what draft PRs are for, and we'll whip it into shape from there.

**Comment by timtebeek** [comment]
@woj-tek it occurred to me that this is a near perfect use case for our Refaster recipes
- https://github.com/openrewrite/rewrite-logging-frameworks/pull/156

Hope you don't mind me getting a head start to get these recipes in. :)

**Comment by timtebeek** [comment]
There are of course additional cases that we could cover, based on what you might be using there. Feel free to inform us of cases not covered yet, and we'll see about adding those too. And note that while this merely changes from JUL to JUL, you could also write recipes to go from JUL to another logging implementation for cases not covered yet.

You should be able to use [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions) to try out the newly added recipes; You'll find that the JUL `Logger.log(Level, ...)` cases are first converted to dedicated methods, and from there to Log4J and onwards if necessary.

**Comment by timtebeek** [comment]
Agree that we're likely not done yet; was doubting if we'd want to open separate issues, but with the details you've provided here I think it's fine to continue with this one a while longer.

> the second part (JUL->slf4j) is still open. I think it's sensible to, based on https://github.com/openrewrite/rewrite-logging-frameworks/pull/156 recipe, to create recipe for JUL->slf4j that reuse yours. What do you think?

The neat thing about automated migration recipes is that they can be chained together. This composite recipe likely gets you most of the way from JUL to SLF4J, without the need for dedicated recipes to go from A to C, since we have recipes to go from A to B and from B to C. 🙃 
```
type: specs.openrewrite.org/v1beta/recipe
name: org.openrewrite.java.logging.slf4j.JulToSlf4j
displayName: Migrate JUL to SLF4J
description: Migrates usage of Java Util Logging (JUL) to using SLF4J directly.
tags:
  - logging
  - java-util-logging
  - slf4j
recipeList:
  - org.openrewrite.java.logging.log4j.JulToLog4j
  - org.openrewrite.java.logging.slf4j.Log4j2ToSlf4j1
```

We can then optionally add dedicated recipes to the above for cases missed so far, such as the `isLoggable` and logger-with-parameters. These new recipes can then optionally go via-log4j, or directly to slf4j. Again, I think a couple of new test cases might be the best way to see what's not covered yet, and from there see what would be needed to cover those. Note that Refaster style recipes are a great fit where they work, but they can not be used everywhere, such as with unpacking that array above.

Happy to explore this together with you. I think now that we have a good start it's easier to extend for better coverage still.

**Comment by timtebeek** [comment]
One thing that we might need to take another look at is the conversion of methods that take in a Supplier for the message; currently they are converted to using `org.slf4j.Logger`, which has no such methods it seems.

For the parameterized method conversions that take in an array we'll likely need a custom `class JulParameterizedToSlf4j extends Recipe { ... }`. That will be a bit more effort, but not too difficult I suppose. The single parameter argument cases we can possibly still cover with Refaster style recipes.

**Comment by knutwannheden** [comment]
Note: We don't yet support the Refaster annotation for varargs method calls.

**Comment by timtebeek** [comment]
> Note: We don't yet support the Refaster annotation for varargs method calls.

Thanks! Had wanted to differentiate between the single argument and array argument cases indeed. Luckily no varargs here, so we can convert more cases easily already.
![image](https://github.com/openrewrite/rewrite-logging-frameworks/assets/1027334/a9373a4b-b428-4a9d-841d-664420c1db55)

**Comment by timtebeek** [comment]
There is still the `org.slf4j.spi.LoggingEventBuilder#log(java.util.function.Supplier<java.lang.String>)` right? That could be a fairly straightforward replacement without the need for `.setMessage("{}").addArgument(() -> ...)`. Again, likely doable with Refaster, such that it should be straightforward to add some tests and try the generated recipe.

For the log method that takes in an array we'll likely want to use a dedicated recipe, with a start generated here
```java
class MyRecipe extends Recipe {

    @Override
    public String getDisplayName() {
        return "My recipe";
    }

    @Override
    public String getDescription() {
        return "This is a description of what the recipe does.";
    }

    @Override
    public TreeVisitor<?, ExecutionContext> getVisitor() {
        MethodMatcher matcher = new MethodMatcher("java.util.logging.Logger log(java.util.logging.Level,java.lang.String,java.lang.Object[])");
        return Preconditions.check(new UsesMethod<>(matcher), new JavaIsoVisitor<>() {
            @Override
            public J.MethodInvocation visitMethodInvocation(J.MethodInvocation method, ExecutionContext ctx) {
                if (matcher.matches(method)) {
                    // TODO do something other than just mark the method as found?
                    return SearchResult.found(method);
                }
                return super.visitMethodInvocation(method, ctx);
            }
        });
    }
}
```

**Comment by timtebeek** [comment]
Great to see these added, thanks a lot! Look forward a (even draft) PR for the parameterized cases as well. I must say this is good fun to tag team on. For any questions feel free to join [our Slack](https://join.slack.com/t/rewriteoss/shared_invite/zt-nj42n3ea-b~62rIHzb3Vo0E1APKCXEA) as well.

**Comment by timtebeek** [comment]
I think we've slowly covered most cases here @woj-tek ; would you agree? We could _maybe_ remove the `sourceClass` and `sourceMethod` arguments from `logp`, and then switch that to `log` such that it gets picked up by the other recipes. Other than that I'm leaning towards closing this generic issue, and opening specific issues whenever anyone wants to see anything new covered.

**Comment by timtebeek** [comment]
Thanks a lot! I've polished up your PR and will see that through to close out this issue. Anything else we can pick up separately from a PR if anyone feels so inclined.

> Btw. is there an easy way to build the recipe library binary and test it locally? I tried but it wasn't very straightforward (ended up with odd version like "0.1.0-SNAPSHOT" and trying to use it failed due to missing dependencies…

By far the easiest is to skip packaging your recipe at all, and immediately run your recipe from your IDE classpath. That way you're able to very quickly get running, set breakpoints, and step through on real projects. Made possible through [our IDE plugin and CLI](https://www.moderne.io/blog/introducing-the-moderne-ide-plugin-for-jetbrains-intellij-idea). Happy to help you set that up!
![image](https://github.com/openrewrite/rewrite-logging-frameworks/assets/1027334/40e2e875-cafb-4871-9e6e-97e47a0e8d02)

Great to see this migration now mostly complete; thanks again for all the work you've put towards this!

**Comment by timtebeek** [comment]
Thanks for reporting your findings here! Probably best to log an issue for each to follow up. The first IndexOutOfBoundsException might warrant a separate recipe that runs first to find and potentially fix such issues, as it would be more widely applicable. Then the JULParameterizedArguments recipe can continue to assume that its input arguments are well formed.
https://github.com/openrewrite/rewrite-logging-frameworks/blob/25726e9e4ecaf3f5c127ce8e1e1ae718c3c58678/src/main/java/org/openrewrite/java/logging/slf4j/JulParameterizedArguments.java#L114-L116

The second case I'd be curious to see more context around. Running the CLI with `--jvm-debug`, or `mvnDebug` might help turn up any such issues. We do usually log more context, but in this case it looks like we're unexpectedly failing deeper down in trying to replace arguments; I'd like to better understand what's going on before we make general changes.
