### ISSUE TITLE
log4j-to-slf4j is intended to rewrite the log4j2 api over to slf4j but framework keeps removing the binding

### ISSUE THREAD

**Issue by hazendaz** [openrewrite/rewrite-logging-frameworks#182]
This has been occurring for a long time and still problem on latest.  It is deleting any occurrence of log4j-to-slf4j 2.x when slf4j is seen.  The entire point of that module is to rewrite the log4j2 api to slf4j api.  It states its part of the removal process in the meta data here when migrating to slf4j.  But this is wrong.  In my case I am using apache poi and need it to write to slf4j.  I don't want to lose those logs. Why would this action occur?

**Comment by timtebeek** [comment]
Hi @hazendaz ; Would you mind conforming to [this bug report format](https://github.com/openrewrite/.github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md)? It's hard for us with the limited time we have to work out the details from a free-form report. That allows us to better judge your issue, and provide guidance on how to see that resolved.

**Comment by timtebeek** [comment]
Needed a second reading before I fully grasped what you were after @hazendaz ;  applied in https://github.com/openrewrite/rewrite-logging-frameworks/commit/7213deaf81765e4d81da8d78f378b3679eb6db88  just now (please check), Thanks again!

**Comment by hazendaz** [comment]
Perfect I can give it a try likely tomorrow.  Thanks!

**Comment by hazendaz** [comment]
> Perfect I can give it a try likely tomorrow. Thanks!

As work life has it, I was not able to get to it today.  I'm going to get to it by Monday at the latest.  I had to procure all the updates in and that took some time and I have to get our master parent pom all setup.  Assuming business needs leave me be tomorrow, I'll be able to test then and I'll report back by latest Monday.  Thanks.

**Comment by timtebeek** [comment]
All good! I've merely removed the step that would have removed the dependency; indeed did not make sense to do so, so I think you should not be having any such issues going forward.

**Comment by hazendaz** [comment]
I've still not been able to confirm this due to other breaks with updates in months since this and then the license change that stopped all ability for us to even use.  We are still working through those issues so it will probably be another month or two before I can confirm this and ran into yet another new issue I raised a ticket for tonight.  I'll still circle back and confirm here when I'm able to.
