### ISSUE TITLE
Log4j1ToLog4j2 recipe does not replace uses of Level.isGreaterOrEqual

### ISSUE THREAD

**Issue by emmulator** [openrewrite/rewrite-logging-frameworks#191]
## What version of OpenRewrite are you using?

rewrite-maven-plugin: 5.46.1
rewrite-logging-frameworks: 2.18.0-SNAPSHOT

## How are you running OpenRewrite?

`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-logging-frameworks:2.18.0-SNAPSHOT -Drewrite.activeRecipes=org.openrewrite.java.logging.log4j.Log4j1ToLog4j2 -Drewrite.exportDatatables=true`

The actual code I'm migrating is a much larger project, but I have replicated the issue with the small code sample below.

## What is the smallest, simplest way to reproduce the problem?

```java
package com.cj.example;

import org.apache.log4j.Level;

public class App {

    public static void main( String[] args ) {
        System.out.println( Level.ERROR.isGreaterOrEqual(Level.INFO) );
    }
}
```

## What did you expect to see?
```java
package com.cj.example;

import org.apache.logging.log4j.Level;

public class App {

    public static void main( String[] args ) {
        System.out.println( Level.ERROR.isMoreSpecificThan(Level.INFO) );
    }
}
```

## What did you see instead?
```java
package com.cj.example;

import org.apache.logging.log4j.Level;

public class App {

    public static void main( String[] args ) {
        System.out.println( Level.ERROR.isGreaterOrEqual(Level.INFO) );
    }
}
```

## What is the full stack trace of any errors you encountered?

There were no errors running the recipe, but the resulting code does not compile.  The old method does not exist on the new version of the class.  The method was inherited from `org.apache.log4j.Priority`, which `Level` used to extend, but which no longer exists in log4j2.

**Comment by timtebeek** [comment]
Thanks for the report @emmulator ! It looks like this should be a fairly straightforward change to add this, looking at this example:
https://github.com/openrewrite/rewrite-logging-frameworks/blob/3492463e8443a6dae646f346f38620e862242d37/src/main/resources/META-INF/rewrite/log4j.yml#L76-L78

Would you be willing to push that up to a draft PR?
