### ISSUE TITLE
Log4j1ToLog4j2 recipe does not replace calls to Logger -> setLevel

### ISSUE THREAD

**Issue by emmulator** [openrewrite/rewrite-logging-frameworks#193]
## What version of OpenRewrite are you using?

rewrite-maven-plugin: 5.46.1
rewrite-logging-frameworks: 2.18.0-SNAPSHOT

## How are you running OpenRewrite?

`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-logging-frameworks:2.18.0-SNAPSHOT -Drewrite.activeRecipes=org.openrewrite.java.logging.log4j.Log4j1ToLog4j2 -Drewrite.exportDatatables=true`

## What is the smallest, simplest way to reproduce the problem?
```java
import org.apache.log4j.Logger;
import org.apache.log4j.Level;

public class App {

    public static void main( String[] args ) {

        Logger logger = Logger.getLogger(App.class);

        logger.info("This should be logged");

        logger.setLevel(Level.WARN);

        logger.info("This should NOT be logged");

    }
}
```

## What did you expect to see?

```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.core.config.Configurator;

public class App {
    
    public static void main( String[] args ) {

        Logger logger = LogManager.getLogger(App.class);

        logger.info("This should be logged");

        Configurator.setLevel(logger, Level.WARN);

        logger.info("This should NOT be logged");

    }
}
```

## What did you see instead?

```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Level;

public class App {

    public static void main( String[] args ) {

        Logger logger = LogManager.getLogger(App.class);

        logger.info("This should be logged");

        logger.setLevel(Level.WARN);

        logger.info("This should NOT be logged");

    }
}
```

## What is the full stack trace of any errors you encountered?

There were no errors running the recipe, but the resulting code does not compile.  Logger no longer has a 'setLevel' method.

**Comment by timtebeek** [comment]
hi @emmulator ; thanks for letting us know! This case is likely most easily resolved through a three line declarative recipe using
https://docs.openrewrite.org/recipes/java/changemethodtargettostatic

Would you want to push that up? I'd noticed you already opened a few other issues as well that we can resolve in a single PR if you're open to getting that started.

**Comment by emmulator** [comment]
Hey @timtebeek , I'm not sure if I'll have the bandwidth to submit anything.  I'm still trying to get through the migration on my end.  It seems that over the years my company has used every aspect of log4j that is no longer supported in log4j2... :)

**Comment by timtebeek** [comment]
Understandable; figured give it a quick shot and looks like this would work:
- https://github.com/openrewrite/rewrite-logging-frameworks/pull/195

Are you able to test that out using [our snapshot versions](https://docs.openrewrite.org/reference/snapshot-instructions)?

**Comment by emmulator** [comment]
Sorry @timtebeek , I didn't notice the notification that you had commented.  Yes, I ran my local test cases for all four issues using the latest snapshot, and they all behaved as expected.  Thanks!

**Comment by timtebeek** [comment]
Thanks for getting back to me! Glad to hear your issues are resolved; hope that helps you in your migration there.
