### ISSUE TITLE
Log4j1ToLog4j2 recipe does not replace uses of Priority

### ISSUE THREAD

**Issue by emmulator** [openrewrite/rewrite-logging-frameworks#194]
## What version of OpenRewrite are you using?

rewrite-maven-plugin: 5.46.1
rewrite-logging-frameworks: 2.18.0-SNAPSHOT

## How are you running OpenRewrite?

`mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.recipeArtifactCoordinates=org.openrewrite.recipe:rewrite-logging-frameworks:2.18.0-SNAPSHOT -Drewrite.activeRecipes=org.openrewrite.java.logging.log4j.Log4j1ToLog4j2 -Drewrite.exportDatatables=true`

## What is the smallest, simplest way to reproduce the problem?
```java
import org.apache.log4j.Logger;
import org.apache.log4j.Priority;

public class App {

    private static Logger logger = Logger.getLogger(App.class);

    public static void main( String[] args ) {

        logger.log(Priority.INFO, "Hello World!" );
    }
}
```

## What did you expect to see?
```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Level;
import org.apache.logging.log4j.LogManager;

public class App {

    private static Logger logger = LogManager.getLogger(App.class);

    public static void main( String[] args ) {

        logger.log(Level.INFO, "Hello World!" );
    }
}
```
or 
```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.LogManager;

public class App {

    private static Logger logger = LogManager.getLogger(App.class);

    public static void main( String[] args ) {

        logger.info( "Hello World!" );
    }
}
```

## What did you see instead?
```java
import org.apache.logging.log4j.Logger;
import org.apache.logging.log4j.Priority;
import org.apache.logging.log4j.LogManager;

public class App {

    private static Logger logger = LogManager.getLogger(App.class);

    public static void main( String[] args ) {

        logger.log(Priority.INFO, "Hello World!" );
    }
}
```

## What is the full stack trace of any errors you encountered?

There were no errors running the recipe, but the resulting code does not compile.  Log4j2 does not include the 'Priority' class.

**Comment by timtebeek** [comment]
Thanks for the complete examples here @emmulator ! I think the `ChangeType` recipe ought to be enough to clear this out.
