### ISSUE TITLE
ParameterizedLogging leaves empty string in first argument sometimes

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-logging-frameworks#35]
![image](https://user-images.githubusercontent.com/1697736/125555291-a65aaae0-0451-448f-9462-39b4cbd8533b.png)

**Comment by aegershman** [comment]
![Screen Shot 2021-07-14 at 3 54 14 PM](https://user-images.githubusercontent.com/5619476/125691497-7f2e15ce-ab57-4f20-ac43-17c19aa8977d.png)

fixed by https://github.com/openrewrite/rewrite-logging-frameworks/commit/ec5cc1729abbd71ad6e88c8df33f95b387cfe085
