### ISSUE TITLE
Unexpected indent on ParameterizedLogging

### ISSUE THREAD

**Issue by jkschneider** [openrewrite/rewrite-logging-frameworks#37]
spring-cloud-dataflow-configuration-metadata/src/test/java/org/springframework/cloud/dataflow/container/registry/authorization/S3SignedRedirectRequestServerResource.java

![image](https://user-images.githubusercontent.com/1697736/125701539-5a753f77-7174-4fc9-9868-3fac15472003.png)

**Comment by aegershman** [comment]
This formatting issue has been resolved 👍 

![Screen Shot 2021-11-03 at 3 21 46 PM](https://user-images.githubusercontent.com/5619476/140186943-a72330c6-fcbd-411f-9ea1-3eaec19f2730.png)
