### ISSUE TITLE
If String.format is used then its not changed

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-logging-frameworks#41]
I was using [errorprone-slf4j](https://github.com/KengoTODA/errorprone-slf4j) on an existing code base where in some places it was using `String.format` and I expected it to be changed b, but it was not.

Here's some sample code of what I'm talking about:

```
Object obj1 = new Object();
Object obj2 = new Object();

LOG.info(String.format("Object 1 is %s and Object 2 is %s", obj1, obj2));
```

The error reported by that tool is:

```
[Slf4jFormatShouldBeConst] SLF4J logging format should be constant value, but it is 'LOG.info(String.format("Object 1 is %s and Object 2 is %s", obj1, obj2));'
```

**Comment by jkschneider** [comment]
Hi @rdifrango 0.10.0 is available in maven central now for your use. There maybe a few more edge cases we need to take care of, but this is a good start.

Also, just FYI for the future, every successful CI build of a rewrite project generates snapshot releases here: https://oss.sonatype.org/content/repositories/snapshots

Lastly, feel free to try it out for yourself on the 65 million lines of OSS code we have pre-parsed. Can use github to login at https://app.moderne.io/recipes/org.openrewrite.java.logging.slf4j.Slf4jLogShouldBeConstant (it's open).

**Comment by rdifrango** [comment]
@jkschneider - yeah that's a fair point, the only problem is that its performance issue but that's on them :). If only SLF4J had lambda based logging like log4j2 then it could be:

```
LOG.info("Performance hit {}", () -> mapper.writeValueAsString(eventData));
```

or perhaps it could result in a guarded check:

```
if (LOG.level == INFO)
{
LOG.info(mapper.writeValueAsString(eventData));
}
```
