### ISSUE TITLE
Support log4j2 conversion

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-logging-frameworks#43]
I was reading the documentation [here](https://docs.openrewrite.org/tutorials/migrate-to-slf4j-from-log4j) and it seemed to indicated that conversion from log42j to slf4j was supported, but when I looked at the code it is classic log4j to slf4j.

It would be nice if there was a recipe to convert from log4j2 to slf4j:

```
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

LogManager.getLogger
```

should mostly be:

```
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

LoggerFactory.getLogger
```

There are probably some edge cases around log4j2's lambda support for parameters and a few others as well.

**Comment by traceyyoshima** [comment]
Hi @rdifrango, thanks for opening an issue - we'll look into it!

**Comment by rdifrango** [comment]
@traceyyoshima happy to help as well, just let me know.

**Comment by aegershman** [comment]
Hey @rdifrango thanks for logging this. The docs should specify log4j classic, true. And log4j2 to slf4j recipes will reference different types than log4j classic. I'm looking into this now 👍

**Comment by aegershman** [comment]
Alrighty @rdifrango I went ahead and merged #44 which should handle migrating Log4J2 types to SLF4J; you can leverage it as `org.openrewrite.java.logging.slf4j.Log4j2ToSlf4j` with the latest `snapshot` of this repository. Try it out where you can; keep in mind, it won't update `log4j.properties` files and such, but it will update the type references.

I'll close this out, but feel free to log any issues in follow-ups and we'll roll from there. If anything at all seems amiss, feel free to log it as an issue and we'll get it worked out as soon as possible 👍  Thanks for your patience on this, and thank you for filing the issue for it. Good catches all around.

**Comment by rdifrango** [comment]
Sorry just getting back to this, what is the SNAPSHOT version?  And is it published in Maven central?

**Comment by aegershman** [comment]
@rdifrango try this out with the latest rewrite-maven-plugin snapshot (4.17.0-SNAPSHOT) and rewrite-testing-frameworks snapshot (1.1.0-SNAPSHOT), from the README: https://github.com/openrewrite/rewrite-maven-plugin#snapshots

If you're using the rewrite-gradle-plugin, we're working on having that be published to maven central as a snapshot, too.

**Comment by rdifrango** [comment]
Thanks...I'll need to see if our internal mirror can see it.
