### ISSUE TITLE
Calls to Exception.getMessage() or Exception.getLocalizedMessage() should be converted

### ISSUE THREAD

**Issue by rdifrango** [openrewrite/rewrite-logging-frameworks#46]
Calls to Exception.getMessage() or Exception.getLocalizedMessage() should be converted to leverage the fact that the last parameter of SLF4J will drop the message and stack trace, aka:

```
logger.warn(e.getMessage());
logger.error(e.getLocalizedMessage());
```

should be converted to something like the following:

```
logger.warn("Error", e);
logger.error("Error", e);
```

**Comment by pway99** [comment]
@rdifrango thanks for the suggestion, we can add a recipe for conversion.  The error message will be configurable with an empty string for the default value.

**Comment by rdifrango** [comment]
@pway99 thanks and that sounds like a good approach...I really should learn how to write my own and contribute them back.
