### ISSUE TITLE
Parameterized Logging parameterizes logging statements even when messages are not concatenated

### ISSUE THREAD

**Issue by pway99** [openrewrite/rewrite-logging-frameworks#58]
![image](https://user-images.githubusercontent.com/22326988/157275028-9d1ce0cf-c9ae-48c0-98ae-a7b67d2b0dee.png)

**Comment by pway99** [comment]
@sambsnyd @tkvangorder 
Closing this issue after a bit more research and reviewing the commit message for the code which performs this action:

> parameterize non-string single-argument objects using double-braces

This seems reasonable to avoid invoking `toString()` on non-string arguments even if the logging level does not apply.

Please feel free to re-open if you disagree.

**Comment by murdos** [comment]
> This seems reasonable to avoid invoking toString() on non-string arguments even if the logging level does not apply.

I don't understand how this change avoid invoking `toString()`.

I've also encountered a strange similar and IMO unneeded change made by [rewrite-logging-frameworks](https://github.com/openrewrite/rewrite-logging-frameworks):

```java
BulkResponse response = restHighLevelClient.bulk(bulkRequest, RequestOptions.DEFAULT);
if (response.hasFailures()) {
    LOGGER.error("{}", response.buildFailureMessage());
}
```

`org.elasticsearch.action.bulk.BulkResponse#buildFailureMessage` has String return type.

**Comment by pway99** [comment]
Hi @murdos,
Thanks for tracking down this issue, I also thought it was a bug to add parameterized logging for single object messages.  

> I don't  understand how this change avoid invoking `toString()`.

Here is a reference to the slf4j faq on logging object messages.    
 
https://www.slf4j.org/faq.html#logging_performance
> **How can I log the string contents of a single (possibly complex) object?**
    In relatively rare cases where the message to be logged is the string form of an object, then the parameterized printing method of the appropriate level can be used. Assuming complexObject is an object of certain complexity, for a log statement of level DEBUG, you can write:
    `logger.debug("{}", complexObject);`
    The logging system will invoke `complexObject.toString()` method only after it has ascertained that the log statement was enabled. Otherwise, the cost of `complexObject.toString()` conversion will be advantageously avoided.
    
The recipe does not attempt to assess the complexity of object or method invocation messages which is why you may find some cases where the conversion is not necessary.

**Comment by murdos** [comment]
@pway99 : thanks for the explanation! Would you accept a request for enhancement that would check method invocation return type as in my previous example?

```java
 BulkResponse response = restHighLevelClient.bulk(bulkRequest, RequestOptions.DEFAULT);
 if (response.hasFailures()) {
     LOGGER.error("{}", response.buildFailureMessage());
 }
 ```

**Comment by pway99** [comment]
Hi @murdos, thanks for following up.  

>Would you accept a request for enhancement that would check method invocation return type as in my previous example?

Of course, it's a reasonable request and an easy update,  I will go ahead and make the change.
