### ISSUE TITLE
Loggers should be named for their enclosing classes. `RSPEC-3416`

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-logging-frameworks#65]
I just commited this one as a result of copying and pasting :)

https://rules.sonarsource.com/java/RSPEC-3416

**Comment by pway99** [comment]
This is a good one thanks @yeikel

**Comment by timtebeek** [comment]
There's a [first attempt](https://github.com/openrewrite/rewrite-logging-frameworks/compare/main...timtebeek:loggers_named_for_enclosing_class?expand=1) in my branch, but somehow I get lots of compile errors when I try to run even the main branch locally, on different JDKs. Is that still working?

**Comment by pway99** [comment]
Could be a missing `rewrite-java-tck` dependency one sec I will have a look
