### ISSUE TITLE
Migrate to slf4j 2.x

### ISSUE THREAD

**Issue by yeikel** [openrewrite/rewrite-logging-frameworks#70]
For Log4j 2, it should : 

- Replace `org.apache.logging.log4j:log4j-slf4j-impl` with `org.apache.logging.log4j:log4j-slf4j2-impl`. See https://logging.apache.org/log4j/2.x/log4j-slf4j-impl/index.html 
- Upgrade slf4j to 2.1 or higher
- Upgrade log4j to 2.19.0 or higher

**Comment by timtebeek** [comment]
Fixed in
- https://github.com/openrewrite/rewrite-logging-frameworks/pull/142
