### ISSUE TITLE
Prevent stacktraces from being removed when passed to logger methods

### ISSUE THREAD

**Issue by sambsnyd** [openrewrite/rewrite-logging-frameworks#96]
It is a common mistake to call `Exception.getMessage()` when passing an exception into a log method. Not all exception types have useful messages, and even if the message is useful this omits the stack trace.

A recipe that removes calls to `getMessage()` within log statements would be an easy win and could be included in the logging best practices recipe

**Comment by kunli2** [comment]
Added `CompleteExceptionLogging` and removed `ConvertLogMessageMessageOnlyToLogMessageAndThrowable` from `Slf4jBestPractices`.
since the former includes the same feature so the latter is redundant.
